### ISSUE TITLE
404 Not Found error

### ISSUE THREAD

**Issue by ksg52** [CHESSComputing/CHAPaaS#7]
I opened http://chapbook.classe.cornell.edu:8181 via Vivaldi on lnx201 (which I was NoMachined into from outside of the lab), and was able to authenticate via GitHub but get a "404 Not Found: You are requesting a page that does not exist!" error where the Jupyter notebook should be when viewing http://chapbook.classe.cornell.edu:8181/notebook.
![chapbook_error](https://github.com/CHESSComputing/CHAPaaS/assets/46967435/942e7f52-7bc5-43c0-bc53-5fd1954a5bd8)

**Comment by vkuznet** [comment]
you may try again visit the page, I saw the directory permission issue which I granted. Let me know if you can access it now.

**Comment by ksg52** [comment]
This worked! I am able to access the notebook and successfully ran the “basic” workflow.

**Comment by vkuznet** [comment]
@arwol, @jpk96 please try again as I saw your github names appeared with similar issue in a CHAPBook log. The underlying issue was misconfiguration of permission on user work area. Please confirm or not in this ticket if it works for you now.

**Comment by vkuznet** [comment]
since issue is resolved I'll close this ticket for now. If @arwol or @jpk96 will still experience the problem please re-open it and provide more details.
